# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2cfa7f1dc7068d9dcde7713d84bf3ef36e2fb272b435b37095dbfc4b03e8ddb9a1e72349290c7fdde3778803d06ce38504a73c9550a153e5f16234360d0a5aad

test:
  secret_key_base: 4d0fee5f949c01fe98a8ff123d8d02f577574ed1db5f753d3bd31cebdeb48aa88cde352e0cc9c544722b7217f161f49a2107fe51911b1e6a073c41c47191dfd3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
